#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i src/icon.ico -n REPLACE src/main.py
# build exe
pyinstaller -y REPLACE.spec
# unix setup
mv dist/REPLACE dist/REPLACE_e
mkdir dist/REPLACE
mv dist/REPLACE_e dist/REPLACE/REPLACE
# copy in assets
cp -r src/assets dist/REPLACE/assets
# copy in license
cp LICENSE.txt dist/REPLACE/
# copy in readme
cp README.txt dist/REPLACE/
# linux cleanup
sed -i 's/REPLACE.exe/REPLACE/g' dist/REPLACE/README.txt
# unix final
chmod +x dist/REPLACE
# cleanup
deactivate
rm -r build
rm REPLACE.spec
