#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i src/icon.ico -n depth-charge src/main.py
# build exe
pyinstaller -y depth-charge.spec
# unix setup
mv dist/depth-charge dist/depth-charge_e
mkdir dist/depth-charge
mv dist/depth-charge_e dist/depth-charge/depth-charge
# copy in assets
cp -r src/assets dist/depth-charge/assets
# copy in license
cp LICENSE.txt dist/depth-charge/
# copy in readme
cp README.txt dist/depth-charge/
# linux cleanup
sed -i 's/depth-charge.exe/depth-charge/g' dist/depth-charge/README.txt
# unix final
chmod +x dist/depth-charge
# cleanup
deactivate
rm -r build
rm depth-charge.spec
