#!/bin/bash

cd ..
# cleanup old build
rm -r dist
# use virtual environment
source src/venv/bin/activate
# get pyinstaller
pip install pyinstaller
# create spec file
pyinstaller --clean -ywF -i src/icon.ico -n DEPTH_CHARGE src/main.py
# build exe
pyinstaller -y DEPTH_CHARGE.spec
# unix setup
mv dist/DEPTH_CHARGE dist/DEPTH_CHARGE_e
mkdir dist/DEPTH_CHARGE
mv dist/DEPTH_CHARGE_e dist/DEPTH_CHARGE/DEPTH_CHARGE
# copy in assets
cp -r src/assets dist/DEPTH_CHARGE/assets
# copy in license
cp LICENSE.txt dist/DEPTH_CHARGE/
# copy in readme
cp README.txt dist/DEPTH_CHARGE/
# linux cleanup
sed -i 's/DEPTH_CHARGE.exe/DEPTH_CHARGE/g' dist/DEPTH_CHARGE/README.txt
# unix final
chmod +x dist/DEPTH_CHARGE
# cleanup
deactivate
rm -r build
rm DEPTH_CHARGE.spec
